server:
  servlet:
    context-path: /sd
  port: 8080

#smartDiet:
#  captcha-expiration: 2
#  profile: /Users/vskendo/smartDiet
#  system-uri: https://127.0.0.1

spring:
  jackson:
    time-zone: GMT-5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.17.69.128:3306/smartDiet?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: smartDietDev
    password: smartDietDev@123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      maxActive: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      testWhileIdle: true
  #      filters: stat,wall,log4j2
  #      filter:
  #        stat:
  #          enabled: true
  #          db-type: mysql
  #          log-slow-sql: true
  #          slow-sql-millis: 1000
  #        slf4j:
  #          enabled: true
  #          statement-log-error-enabled: true
  #          statement-create-after-log-enabled: false
  #          statement-close-after-log-enabled: false
  #          result-set-open-after-log-enabled: false
  #          result-set-close-after-log-enabled: false
  #      web-stat-filter:
  #        enabled: true
  #        url-pattern: /*
  #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  #        session-stat-enable: true
  #        session-stat-max-count: 1000
  #      stat-view-servlet:
  #        enabled: true
  #        url-pattern: /druid/*
  #        reset-enable: false
  #        login-username: root
  #        login-password: 123
#  redis:
#    database: 3
#    port: 6379
#    host: localhost
